"use client";
import { useReducer, useState } from "react";
import { ArrowRight, Paperclip, RotateCcw } from "lucide-react";
import { initialShift, shiftEvents, shiftReducer } from "@/lib/shift-simulation";
import styles from "./approval.module.css";
export function ShiftExperiment(){
 const [state,dispatch]=useReducer(shiftReducer,initialShift);const [confirm,setConfirm]=useState(false);
 const next=shiftEvents[state.cursor];const complete=state.records.includes('A-in')&&state.records.includes('A-out');
 function reset(){dispatch({type:'reset'});setConfirm(false);}
 return <section className={`${styles.board} ${styles.shift}`} aria-label="Attendance shift simulation"><Paperclip className={styles.clip} size={45} aria-hidden="true"/>
 <div className={styles.top}><div><p className={styles.label}>FACTORY ATTENDANCE / INTERACTIVE SIMULATION</p><h2>One shift.<br/>A few edge cases.</h2><p>Follow fictional operators through a 22:00–06:00 overnight shift. Decide what belongs in the report.</p></div><aside className={styles.sticky}>Uncertainty needs<br/><u>a human.</u></aside></div>
 <p className={styles.disclosure}>Synthetic events only. No camera, facial recognition, employee data, or payroll connection.</p>
 <ol className={styles.pipeline} aria-label="Attendance workflow"><li>Capture</li><li><ArrowRight aria-hidden="true"/>Review</li><li><ArrowRight aria-hidden="true"/>Replay</li><li><ArrowRight aria-hidden="true"/>Report</li></ol>
 <div className={styles.desk}><article className={styles.proposal}><p className={styles.label}>01 / PLAY THE SHIFT · {state.cursor}/{shiftEvents.length}</p><h3>{next?next.title:'Shift events complete.'}</h3><p>{next?next.time:'Inspect the report and resolve any remaining exception.'}</p><div className={styles.actions}><button disabled={!next} onClick={()=>dispatch({type:'next'})}>Next event <ArrowRight size={16} aria-hidden="true"/></button><button onClick={reset}><RotateCcw size={15} aria-hidden="true"/>Reset & replay</button></div>
 <p className={styles.note}>Device: {state.online?'connected':'offline'} · {state.buffered.length} buffered</p>
 <h3 className={styles.logTitle}>The event trail</h3><ol className={styles.history} aria-label="Event history">{state.history.map((event,i)=><li key={i}>{event}</li>)}</ol>{!state.history.length&&<p>No events yet. Start with the first arrival.</p>}
 </article><div><article className={styles.receipt} aria-label="Sample attendance report"><p className={styles.label}>02 / THE SAMPLE REPORT</p><h3>Recorded ≠ assumed.</h3><dl className={styles.results}><div><dt>Accepted punches</dt><dd>{state.records.length}</dd></div><div><dt>Operator A · in</dt><dd>{state.records.includes('A-in')?'Day 1 · 21:58':'Not recorded'}</dd></div><div><dt>Operator A · out</dt><dd>{state.records.includes('A-out')?'Day 2 · 06:04':'Not recorded'}</dd></div><div><dt>Recorded interval</dt><dd>{complete?'8h 06m':'Incomplete'}</dd></div><div><dt>Operator B</dt><dd>{state.exception==='accepted'?'In only · incomplete':state.exception==='pending'?'Held for review':'No accepted punch'}</dd></div></dl><p className={styles.boundary}>The interval crosses midnight. It is elapsed time between sample punches, not payable hours; breaks and payroll rules are not modeled.</p></article>
 <article className={styles.exception}><p className={styles.label}>03 / HUMAN EXCEPTION QUEUE</p><div role="status" aria-live="polite"><p>{state.exception==='pending'?'Operator B · 22:01. Match is uncertain. Keep it out of the report until a supervisor decides.':state.exception==='accepted'?'Supervisor accepted the sample punch. B still has no checkout.':state.exception==='dismissed'?'Supervisor dismissed the sample punch. It stays out of the report.':'No pending exception.'}</p><p className={styles.srStatus}>{state.history.at(-1)}</p></div>{state.exception==='pending'&&<div className={styles.actions}><button onClick={()=>dispatch({type:'accept'})}>Accept sample punch</button><button onClick={()=>dispatch({type:'dismiss'})}>Dismiss punch</button></div>}</article></div></div>
 <details className={styles.explain}><summary>Sample-data controls / clear this report</summary><p>Clears the fictional records, event history, exception decision and buffered punches in this browser component. Reset restores the initial scenario. Nothing is sent to a server.</p>{confirm?<div className={styles.actions}><button onClick={()=>{dispatch({type:'clear'});setConfirm(false);}}>Confirm clear sample data</button><button onClick={()=>setConfirm(false)}>Keep sample data</button></div>:<button className={styles.reset} onClick={()=>setConfirm(true)}>Clear sample data…</button>}</details>
 </section>;
}
